name: Docs
on:
    workflow_dispatch:
    push:
      branches: main
      paths: docs/**
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: write_docs
      - name: Commit and Push
        run: |
          git config --global user.name 'Quarto'
          git commit -am "Automated rendering by Quarto"
          git push
      - name: GitHub Pages
        uses: actions/configure-pages@v3