project:
  type: website
  output-dir: build-docs

website:
  title: "Python User's Guide"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Tools"
        menu:
          - href: tools/overview.qmd
            text: Overview
          - href: tools/ide.qmd
            text: Integrated Development Environments
          - href: tools/environment.qmd
            text: Package and Environment Managers
          - href: tools/version_control.qmd
            text: Version Control
          - href: tools/documentation.qmd
            text: Documentation
          - href: tools/containers.qmd
            text: Containerization
      - text: Tutorials
        menu:
          - href: tutorials/vscode_primer.qmd
            text: VS Code Primer
    tools:
      icon: github
      menu:
        - text: Source Repo
          url: https://github.com/gcoyle83/python-starter-template
        - text: Report a Bug
          url: https://github.com/gcoyle83/python-starter-template/issues
  back-to-top-navigation: true
  
format:
  html:
    theme: solarized-dark
    css: styles.css
    toc: true

execute:
  freeze: auto
