project:
  type: website
  output-dir: build-docs

website:
  title: "Python Starter Template"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tools.qmd

format:
  html:
    theme: solarized-dark
    css: styles.css
    toc: true

execute:
  freeze: auto
